SELECT 
    REPORTING_PERIOD,
    FK_CD_COMPUTED_AMOUNT_TYPE,
    S2_LEGAL_ENTITY,
    FK_RW_ISO_CURRENCY_EUR,
    COMPUTED_AMT_EUR
FROM
    /*Update CALCRUN below*/
    CALC6754.FC_COMPUTED_AMOUNTS
    /*Update CALCRUN above*/
WHERE 
    S2_LEGAL_ENTITY = 'D45'
     AND FK_CD_COMPUTED_AMOUNT_TYPE = 'MKTfx'