SELECT
    '2022Q2', 'CALC6935', 
    ES.FK_RW_ISO_CURRENCY,
    ES.FK_RW_ATRADIUS_COMPANY_LE LE, FK_RW_ISO_COUNTRY ISO_COUNTRY,
    CASE WHEN SII_TREATMENT_TYPE = 'ON_SII_BSHEET' THEN 'INVESTMENT' ELSE 'PENSION' END SOURCE,
    EQUITY_CATEGORY CATEGORY,
    EQUITY_TYP TYPE,
    DECODE(EQUITY_CATEGORY, 'STRATEGIC', NULL,
        CASE WHEN ES.PURCHASE_DATE < TO_DATE(20160101, 'YYYYMMDD') THEN '<2016' 
            ELSE '>=2016' END) PURCHASE_DATE,
    ES.SHOCK_FACTOR,
    SUM(ES.MARKET_VAL_LE / FX.CONVERSION_RATE) AS EQUITY_EUR
FROM
    CALC6935.IR_EQUITY_SHOCKED ES,
    CALC6935.RW_CURRENCY_EXCHANGE_RATE FX
WHERE 
    FX.PK_FK_RW_ISO_CURRENCY_SOURCE = 'EUR'
    AND FX.PK_FK_CURR_CONVERSION_TYP = 'VAR'
    AND ES.FK_RW_ISO_CURRENCY__LE = FX.PK_FK_RW_ISO_CURRENCY_TARGET
GROUP BY 
    ES.FK_RW_ATRADIUS_COMPANY_LE, FK_RW_ISO_COUNTRY,
    ES.FK_RW_ISO_CURRENCY,
    CASE WHEN SII_TREATMENT_TYPE = 'ON_SII_BSHEET' THEN 'INVESTMENT' ELSE 'PENSION' END,
    EQUITY_CATEGORY,
    EQUITY_TYP,
    DECODE(EQUITY_CATEGORY, 'STRATEGIC', NULL,
        CASE WHEN ES.PURCHASE_DATE < TO_DATE(20160101, 'YYYYMMDD') THEN '<2016' 
            ELSE '>=2016' END),
    ES.SHOCK_FACTOR,
    ES.FK_RW_ATRADIUS_COMPANY_LE;
