SELECT 
    REPORTING_PERIOD as REPORTING_DAT,
    FK_CD_COMPUTED_AMOUNT_TYPE,
    S2_LEGAL_ENTITY,
    FK_RW_ISO_CURRENCY_EUR,
    COMPUTED_AMT_EUR
/* update Schema below */
FROM CALCXXXX.FC_COMPUTED_AMOUNTS
/* update Schema above */
WHERE 
    S2_LEGAL_ENTITY = 'D45'
    AND FK_CD_COMPUTED_AMOUNT_TYPE = 'MKTeq'
