SELECT
    eq.REPORTING_DAT,
    eq.ISSUER_IDENTIFIER AS ISSUER_ID,
    als.ALIAS_NAME,
    eq.COUNTRY_CODE,
    CONCAT(eq.EQUITY_CATEGORY, eq.EQUITY_TYP) AS EQUITYCATEGORY,
    eq.EQUITY_TYP,
    eq.EQUITY_IDENTIFIER AS EQUITY_ID,
    eq.ECAI,
    eq.U_ECAI,
    eq.SECTOR,
    eq.SUBPORTFOLIO,
    eq.PURCHASE_DAT,
    eq.SOLVENCY_II_VALUATION AS SOL_II_VAL,
    eq.FUNCTIONAL_CURRENCY_CODE,
    fx.CONVERSION_RATE AS FX_RATE,
    (eq.SOLVENCY_II_VALUATION / fx.CONVERSION_RATE) AS SOL_II_VAL_EUR
FROM
    EDWQ3.TBSL_EQUITIES eq,
    EDWQ3.TBSL_ALIASES als,
    EDWQ3.TBSL_CURR_EXCHANGE_RATES fx
WHERE
    /*AtRe branch code*/
    eq.BRANCH_CODE IN ('277','279')
    /*Month end FX-rate (VAR)*/
    AND fx.CONVERSION_TYPE_CODE = 'VAR'
    /*Connecting tables*/
    AND eq.FUNCTIONAL_CURRENCY_CODE = fx.TARGET_CURRENCY (+)
    AND eq.ISSUER_IDENTIFIER = als.ALIAS_IDENTIFIER (+)
    AND eq.ISSUER_IDENTIFIER = als.ALIAS_IDENTIFIER (+)
    AND eq.ALIAS_TYPE_CODE = als.ALIAS_TYPE_CODE (+)
