SELECT 
    bval.REPORTING_DAT,
    b.BOND_IDENTIFIER,
    bval.ASSET_MANAGER,
    b.COUNTERPARTY_RISK_TYPE_CODE,
    b.ISSUER_IDENTIFIER AS ISSUER_ID,
    b.ISSUER_DES,
    b.ISSUER_GROUP_DES,
    b.SECTOR,
    b.NOMINAL_VALUE,
    b.BOND_CURRENCY_CODE,
    fx.CONVERSION_RATE AS FX_RATE,
    b.COUNTRY_CODE,
    b.TYPE_OF_BOND,
    b.MATURITY_DAT,
    bval.MODIFIED_DURATION,
    bval.ECAI,
    bval.U_ECAI,
    bval.MARKET_VALUE,
    (bval.MARKET_VALUE / fx.CONVERSION_RATE) AS MARKET_VALUE_EUR,
    CASE
        WHEN bval.MODIFIED_DURATION <= 5 THEN 5
        WHEN bval.MODIFIED_DURATION <= 10 THEN 10
        WHEN bval.MODIFIED_DURATION <= 15 THEN 15
        WHEN bval.MODIFIED_DURATION <= 20 THEN 20
        ELSE 9999
    END AS DURATION_END_YEAR,
    (b.MATURITY_DAT - bval.REPORTING_DAT) / 365.25 AS DURATION_TO_MATURITY,
    FLOOR((b.MATURITY_DAT - bval.REPORTING_DAT) * 4 / 365.25) AS DURATION_QTR,
    FLOOR((b.MATURITY_DAT - bval.REPORTING_DAT) / 365.25) AS DURATION_YR
FROM
    EDWQ3.TBSL_BONDS b,
    EDWQ3.TBSL_BOND_HOLDING_VALS bval,
    EDWQ3.TBSL_CURR_EXCHANGE_RATES fx
WHERE
    b.BOND_IDENTIFIER = bval.BOND_IDENTIFIER
    AND b.DATA_SOURCE_CODE = bval.DATA_SOURCE_CODE
    AND bval.BRANCH_CODE in ('277','279')
    /*FX Parameters*/
    AND fx.CONVERSION_TYPE_CODE = 'VAR'
    AND b.BOND_CURRENCY_CODE = fx.TARGET_CURRENCY
