select EQUITY_IDENTIFIER, SOLVENCY_II_VALUATION, SUBPORTFOLIO
-- select *
from CALCxxxx.RW_EQUITY a
    left join CALCxxxx.RW_ALIAS b
        on a.PK_FK_RW_ALIAS_ALIASID_ISSUER = b.PK_ALIAS_ID
        and a.PK_FK_RW_ALIAS_DATASRC = b.PK_FK_RW_DATA_SOURCE
where a.PK_FK_RW_ATRADIUS_COMPANY in ('277','279')    
and b.GROUP_ID = ''    
order by EQUITY_IDENTIFIER, SUBPORTFOLIO
