SELECT
    MODEL_TYPE,
    MODEL_SUB_TYPE,
    COUNT(CREDIT_LIMIT_ID) AS CREDIT_LIMIT_COUNT,
    SUM)CREDIT_LIMIT_GROSS_EXPOSURE) AS GROSS_EXPOSURE,
    SUM(EXPECTED_LOSS) AS EXPECTED_LOSS,
    SUM(VAR_CONSUMPTION_GR) AS VAR_CONSUMPTION_GR,
    SUM(EL_CONSUMPTION_GR) AS EL_CONSUMPTION_GR,
    SUM(EC_CONSUMPTION_GR) AS EC_CONSUMPTION_GR,
    SUM(VAR_CONSUMPTION_ND) AS VAR_CONSUMPTION_ND,
    SUM(EL_CONSUMPTION_ND) AS EL_CONSUMPTION_ND,
    SUM(EC_CONSUMPTION_ND) AS EC_CONSUMPTION_ND
FROM
    CALC&CALCVAR..SO_REPORTING
GROUP BY
    MODEL_TYPE,
    MODEL_SUB_TYPE
ORDER BY
    MODEL_TYPE,
    MODEL_SUB_TYPE
